# Generated by Django 4.0.3 on 2022-05-09 13:49

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(default='PA', max_length=2),
            preserve_default=False,
        ),
    ]
