# Generated by Django 4.0.3 on 2022-05-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSelections',
        ),
    ]
