# Generated by Django 4.0.3 on 2022-05-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_email_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
