# Generated by Django 4.0.3 on 2022-05-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('order', '0005_order_delivery_instructions_alter_order_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_option', to='checkout.deliveryoptions'),
            preserve_default=False,
        ),
    ]
